version: '2'
services:
    app:
        image: ${app_server}
        external_links:
            - mariadb:mariadb
#        environment:
#            - SPRING_PROFILES_ACTIVE=prod,swagger
#            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/foojhipster
#            - SERVER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mariadb:
        extends:
            file: mariadb.yml
            service: mariadb
