version: '2'
services:
    foojhipster-mariadb:
        container_name: foojhipster-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/foojhipster/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=foojhipster
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
