version: '2'
services:
    bananatree-app:
        image: bananatree-server
        external_links:
            - bananatree-db:mariadb
        environment:
#            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/bananatree
            - SERVER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bananatree-db:
        extends:
            file: mariadb.yml
            service: bananatree-db
