version: '2'
services:
    bananatree-db:
        container_name: bananatree-db
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/foojhipster/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=bananatree
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
